INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (1, 'Dziki Młyn', NULL, 'Warszawa', '2010-03-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (2, 'Panorama', NULL, 'Gdańsk', '2010-03-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (3, 'Franz Josef', NULL, 'Katowice', '2010-03-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (4, 'Impuls', NULL, 'Łódź', '2010-03-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (5, 'Artemis', 'Tawerna Kapetanis', 'Poznań', '2010-04-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (6, 'Pod Arsenałem', NULL, 'Toruń', '2010-04-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (7, 'U Zosi', NULL, 'Szczawnica', '2010-05-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (8, 'Grande Azzurro', 'Alpejska Dolina', 'Warszawa', '2010-05-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (9, 'Pod Żaglami', NULL, 'Olsztyn', '2010-09-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (10, 'Jesz Burger', NULL, 'Lublin', '2010-09-11', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (11, 'Cinamon Cafe', NULL, 'Racibórz', '2010-09-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (12, 'Incognito Club ', 'Weranda', 'Mrozy', '2010-09-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (13, 'Wook and Roll', 'Phi Long', 'Warszawa', '2010-10-02', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (14, 'Zamkowa', NULL, 'Toruń', '2010-10-16', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (15, 'Restauracja Słowiańska', NULL, 'Słońsk', '2010-10-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (16, 'Broniszówka', NULL, 'Bronisze', '2010-10-30', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (17, 'Zamkowa', NULL, 'Świdwin', '2010-11-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (18, 'Paroles Paroles', NULL, 'Kraków', '2010-11-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (19, 'Zajazd Horolna', NULL, 'Przybędza', '2010-11-20', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (20, 'Czarcia Łapa', NULL, 'Lublin', '2010-11-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (21, 'Tabun', NULL, 'Otomin', '2010-12-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (22, 'Tawerna Dominikańska', NULL, 'Gdańsk', '2010-12-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (23, 'Obrochtówka', NULL, 'Zakopane', '2011-02-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (24, 'Colloseum', 'Pod Prosiakiem', 'Tychy', '2011-02-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (25, 'Peper’s', NULL, 'Białystok', '2011-02-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (26, 'Kuchnia i Wino', NULL, 'Pszczyna', '2011-03-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (27, 'Alchemik', NULL, 'Tomaszów Mazowiecki', '2011-03-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (28, 'Indian Ocean', NULL, 'Poznań', '2011-03-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (29, 'Maxim', NULL, 'Wieliczka', '2011-03-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (30, 'Valencia ', 'U Samuela', 'Warszawa', '2011-04-02', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (31, 'U Jędzy', 'Edelweiss', 'Kraków', '2011-04-09', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (32, 'Barcelonka', NULL, 'Przemyśl', '2011-04-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (33, 'Barbarossa', 'Pod Różą', 'Siedlce', '2011-04-23', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (34, 'Darjan-Brydż', 'Zielone Drzewo', 'Bystrzyca Kłodzka', '2011-04-30', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (35, 'Open Air', 'Ale Bajka', 'Magdalenka', '2011-09-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (36, 'Steak House Rodeo', NULL, 'Kwidzyn', '2011-09-15', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (37, 'Panorama', 'Wiszące Ogrody nad Narwią', 'Nowogród', '2011-09-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (38, 'Penelopa', NULL, 'Inowrocław', '2011-09-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (39, 'Ania z Zielonego Wzgórza', 'Don Kichot', 'Tarnowskie Góry', '2011-10-06', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (40, 'Karczma przy Dworze', NULL, 'Jasionka', '2011-10-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (41, 'Braterska', NULL, 'Tarnów', '2011-10-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (42, 'Li Du', NULL, 'Warszawa', '2011-10-27', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (43, 'Stara Kuźnia', NULL, 'Magnuszew', '2011-11-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (44, 'Galeria Smaku', NULL, 'Kozienice', '2011-11-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (45, 'Stella Café', NULL, 'Lębork', '2011-11-17', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (46, 'Karczma Nałęczowska', NULL, 'Nałęczów', '2011-11-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (47, 'Karczma Polany', NULL, 'Kościelisko', '2011-12-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (48, 'Zapiecek', 'Metka', 'Poznań', '2011-12-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (49, 'Kapitan Nemo', 'Kapitan Kuk', 'Skarbimierz-Osiedle', '2012-03-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (50, 'Karczma u Bartka ', 'Kiełbacha i Korale', 'Bukowina Tatrzańska', '2012-03-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (51, 'Tawerna', 'Bar Familijny', 'Dobre Miasto', '2012-03-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (52, 'Syrenka', 'Restauracja Pomorska „Syrenka Ustecka”', 'Ustka', '2012-03-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (53, 'Enigma', 'Pyszny Browar', 'Radom', '2012-03-29', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (54, 'Greek Zorbas', NULL, 'Augustów', '2012-04-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (55, 'Campo di Fiori', 'Laboratorium Pizza', 'Nowy Sącz', '2012-04-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (56, 'Samui', NULL, 'Kraków', '2012-04-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (57, 'Niebieski Parasol', 'Pod Jeleniem', 'Chojnów', '2012-04-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (58, 'Hotel Corum', 'Śniadaniarnia', 'Karpacz', '2012-05-03', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (59, 'New Namaste India', NULL, 'Zielona Góra', '2012-05-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (60, 'Pałac Nieznanice', NULL, 'Nieznanice', '2012-05-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (61, 'Karczma pod Łosiem', 'Farma Wawrzyńca', 'Wawrów', '2012-05-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (62, 'Fregata', NULL, 'Koszalin', '2012-05-31', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (63, 'Kameralna', NULL, 'Chodzież', '2012-09-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (64, 'Magnolia', 'Obora', 'Gryfów Śląski', '2012-09-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (65, 'Leśna Chata', NULL, 'Kraszków', '2012-09-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (66, 'Łabędź', NULL, 'Pyskowice', '2012-09-27', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (67, 'Antykwariat', 'Ąka', 'Lublin', '2012-10-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (68, 'Leo Libra', 'Dziki dwór pod kaczką', 'Gniezno', '2012-10-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (69, 'Kuźnia Smaków', 'Trattoria da Tadeusz', 'Bielsko-Biała', '2012-10-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (70, 'Orient Express', NULL, 'Lublin', '2012-10-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (71, 'Zajazd pod Jodłową Górą', NULL, 'Tymbark', '2012-11-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (72, 'Matalmara', 'Willa pod złotym ziemniakiem', 'Goczałkowice-Zdrój', '2012-11-08', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (73, 'Karczma Leśniczanka', NULL, 'Wielbark', '2012-11-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (74, 'Villa Toscania', NULL, 'Nowe Gorzycko', '2012-11-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (75, 'Gaumarjos', NULL, 'Warszawa', '2012-11-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (76, 'Folklor', NULL, 'Jastrowie', '2013-02-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (77, 'Cieszyński Browar Mieszczański', NULL, 'Cieszyn', '2013-03-07', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (78, 'Rybka', NULL, 'Gdańsk', '2013-03-14', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (79, 'Nasza Chata Smaków', 'Schabowy... Raz!', 'Babi Dół', '2013-03-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (80, 'Magistrat', NULL, 'Hrubieszów', '2013-03-28', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (81, 'Marrone', 'Golonka w Pepitkę', 'Ostrów Wielkopolski', '2013-04-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (82, 'VooDoo', 'American Home', 'Kielce', '2013-04-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (83, 'Carska', NULL, 'Legionowo', '2013-04-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (84, 'Perła', 'U Schabińskiej', 'Jasło', '2013-04-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (85, 'Majag', 'U sióstr', 'Dębica', '2013-05-02', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (86, 'Tawerna Ellada', 'Viva Grecja', 'Głogów', '2013-05-09', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (87, 'Malinówka', NULL, 'Wisła', '2013-05-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (88, 'Viki Lektiko', 'Szprota', 'Elbląg', '2013-05-23', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (89, 'Bazylia & Oregano', NULL, 'Poznań', '2013-05-30', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (90, 'Stary kredens', NULL, 'Sanok', '2013-06-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (91, 'Łebska chata', NULL, 'Łeba', '2014-03-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (92, 'Thai Spa & Restaurant', 'Pad Thai', 'Poznań', '2014-03-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (93, 'Black Jack', 'Ciao Ciao!', 'Słupsk', '2014-03-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (94, 'Zajazd rudzki', 'Bufet rulandia', 'Ruda Śląska', '2014-03-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (95, 'Zośka', NULL, 'Zakopane', '2014-04-03', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (96, 'Italia', 'Casa di Fulvio Maria Viola', 'Bielsko-Biała', '2014-04-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (97, 'Bistro pod aniołami', 'Madame', 'Nysa', '2014-04-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (98, 'La Costa', 'Bistro Bochenek', 'Herby', '2014-04-24', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (99, 'Zajazd Pod Zamkiem', NULL, 'Kętrzyn', '2014-05-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (100, 'Pizzeria OdNowa', 'Chleb & Sól', 'Bochnia', '2014-05-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (101, 'STOP Restaurant', 'Bistro Jajo', 'Białogard', '2014-05-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (102, 'La Torre', 'Mee...lina Bar', 'Miłakowo', '2014-05-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (103, 'Villa "Bianco"', 'Steak & Lobster', 'Wrocław', '2014-05-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (104, 'Gościniec myśliwski', NULL, 'Gdańsk', '2014-09-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (105, 'Bufet Country', NULL, 'Kobiór', '2014-09-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (106, 'Milennium', 'Mio Angel', 'Tczew', '2014-09-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (107, 'Karczma Jurand', 'Przystanek Łosoś', 'Egiertowo', '2014-09-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (108, 'Sekrety Buska', NULL, 'Busko-Zdrój', '2014-10-02', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (109, 'El Mundo', 'Pod cielakiem', 'Gdańsk', '2014-10-09', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (110, 'Gęsia Szyja ', 'Gęsie Sprawki', 'Chełm', '2014-10-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (111, 'Szachownica ', 'Francja Elegancja', 'Poznań', '2014-10-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (112, 'Rancho pod strusiem', NULL, 'Bielsko-Biała', '2014-10-30', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (113, 'Karczma Śląska', 'Pyza Śląska', 'Dąbrowa Górnicza', '2014-11-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (114, 'Restauracja Cechowa', NULL, 'Złotów', '2014-11-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (115, 'China Food', ' Pierożkarnia', 'Grajewo', '2014-11-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (116, 'Imperium', 'Długi Wąż', 'Przasnysz', '2014-11-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (117, 'La Cubanita', 'Casa de Locos', 'Sandomierz', '2015-03-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (118, 'West End', 'Lemon Capri', 'Piła', '2015-03-12', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (119, 'Pod Złotym Aniołem', NULL, 'Bolesławiec', '2015-03-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (120, 'U’Bares', NULL, 'Rzeszów', '2015-03-26', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (121, 'Stary Browar', 'Manufaktura', 'Świdnica', '2015-04-02', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (122, 'Młyn', NULL, 'Bytów', '2015-04-09', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (123, 'Polskie Ranczo', NULL, 'Bestwinka', '2015-04-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (124, 'Remus', ' Sielawka', 'Borowo', '2015-04-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (125, 'Polski Smak', 'Bar Urlop', 'Katowice', '2015-04-30', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (126, 'Dzikie Wino', 'Świnka i Rybka', 'Reda', '2015-05-07', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (127, 'Filmowa', 'Hej Sokoły', 'Kamieniec Wrocławski', '2015-05-14', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (128, 'Figaro', ' Duchówka', 'Elbląg', '2015-05-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (129, 'Zielarnia', NULL, 'Olsztynek', '2015-05-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (130, 'Czardasz', NULL, 'Gdańsk', '2015-09-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (131, 'Tbilisi', NULL, 'Warszawa', '2015-09-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (132, 'Good Father', 'Bistro Bzik', 'Katowice', '2015-09-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (133, 'Charlie’s', 'Charlie’s Star', 'Nowy Dwór Mazowiecki', '2015-09-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (134, 'Karczma Górecka', 'Owce i Róża', 'Brenna', '2015-10-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (135, 'Gusto', 'La Bambola', 'Piaseczno', '2015-10-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (136, 'U Dunina', 'Krochmal', 'Piotrków Trybunalski', '2015-10-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (137, 'Berhida', 'Sowa Nasza Kasza', 'Sanok', '2015-10-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (138, 'Dymarka', 'Wypas', 'Dąbrówki', '2015-10-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (139, 'Boczek i spółka', 'Chrup Chrup Kartofel', 'Jelcz-Laskowice', '2015-11-05', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (140, 'Relax', 'Batory', 'Bielsko-Biała', '2015-11-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (141, 'Gospoda', 'Dzika Świnia', 'Gubin', '2015-11-19', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (142, 'Bistro Obora', 'Zajezdnia', 'Zielonki', '2015-11-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (143, 'El Toro', NULL, 'Łódź', '2015-12-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (144, 'El Fuego', 'Kolorowe Gary', 'Rąbień', '2015-12-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (145, 'Bar u Marka', 'Kugel', 'Knyszyn', '2016-02-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (146, 'Mazowianka', 'Zwyczajna i kiełbasiarnia', 'Mińsk Mazowiecki', '2016-02-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (147, 'Aramia', NULL, 'Szczecin', '2016-03-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (148, 'U Wiencka', 'Uncle Michael Restaurant', 'Komorów', '2016-03-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (149, 'Kaskada smaku', 'Zawijane Bistro', 'Pruszcz Gdański', '2016-03-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (150, 'L’amore', 'Grande Cozze', 'Kielce', '2016-03-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (151, 'Salon kulinarny', 'Abażur', 'Warszawa', '2016-03-31', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (152, 'Pizzeria Kwadrans', 'Zapiekane', 'Brzeziny', '2016-04-07', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (153, 'Karczma Sidło', 'Śledzik', 'Żukowo', '2016-04-14', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (154, 'Pablo Picasso', 'Pod Gołąbkiem', 'Rzeszów', '2016-04-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (155, 'Juran', 'Oberża Żar', 'Dąbrowa Górnicza', '2016-04-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (156, 'Jadłodajnia Bartosz', 'Wyszynk z Szynką', 'Kielce', '2016-05-05', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (157, 'Papalina', NULL, 'Warszawa', '2016-05-12', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (158, 'Ognisty Smok', 'Phúc Phúc', 'Lubartów', '2016-05-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (159, 'Piekielna Kuchnia', 'Nie, bo mleczne', 'Wałbrzych', '2016-09-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (160, 'Szalotka', 'Szarlotka z rumieńcem', 'Łagów', '2016-09-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (161, 'Montenegro', NULL, 'Łódź', '2016-09-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (162, 'Karczma Styrnol ', 'Dzika Chata', 'Zawoja', '2016-09-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (163, 'Cynamon', 'Słoneczna Miska', 'Skrzynki', '2016-09-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (164, 'Blue Moon', NULL, 'Wałcz', '2016-10-06', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (165, 'Domowy Zaułek', 'Prawdziwa Knajpka', 'Lwówek', '2016-10-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (166, 'Bistro Oliwka', 'Bistro La Rosa', 'Łódź', '2016-10-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (167, 'Bar Na Szybkiej', 'Przystanek Wrocek', 'Wrocław', '2016-10-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (168, 'Stacja Kościelniki', 'Gęś na jaśku', 'Kościelniki Górne', '2016-11-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (169, 'Garnuszek', 'Twoja Kolejka', 'Łodygowice', '2016-11-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (170, 'Trzy Smaki', 'Cała Wstecz', 'Czeladź', '2016-11-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (171, 'Chata Po Zbóju', 'Pyszna Stajenka', 'Bąków', '2016-11-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (172, 'Karczma Cykada', 'Gość w Dom', 'Chlastawa', '2016-12-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (173, 'Karczma Zamczysko', 'Bistro na Fali', 'Malbork', '2016-12-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (174, 'Lawendowy Dom', 'Francuska Bajadera', 'Czeladź', '2017-02-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (175, 'Pizzeria Solare', 'La Casa Del Polacco', 'Biała Podlaska', '2017-02-23', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (176, 'Zajazd w Strażnicy', 'Biała Choina', 'Ujsoły', '2017-03-02', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (177, 'Szafran', 'Wałkowane', 'Łódź', '2017-03-09', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (178, 'Restauracja Rodzinna', 'Restauracja Miedziana', 'Lubin', '2017-03-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (179, 'Italian House', 'La Nonna Siciliana', 'Toruń', '2017-03-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (180, 'Przedzamcze', 'Dom Restauracja Sztum', 'Sztum', '2017-03-30', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (181, 'Zajazd u Stefana', 'Karpiówka', 'Odolanów', '2017-04-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (182, 'Na Skarpie', 'Gęsia Nóżka', 'Radziejów', '2017-04-13', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (183, 'Rammer Jammer', 'Gar Na Gazie', 'Głogówek', '2017-04-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (184, 'Bar na Stawkach', 'Gospoda Jagoda', 'Ostrowiec Świętokrzyski', '2017-04-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (185, 'Lizawka', NULL, 'Poznań', '2017-05-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (186, 'Bajkowa', 'Piknik w kratkę', 'Swarzędz', '2017-05-11', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (187, 'Fang Youn', 'Gong Ji', 'Ostróda', '2017-05-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (188, 'Pizzeria "Sale & Pepe”', 'Il Pino', 'Sosnowiec', '2017-09-07', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (189, 'Ślonsko gościno', 'Restauracja Modra', 'Tarnowskie Góry', '2017-09-14', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (190, 'Stare mury', 'Utarte', 'Chrzanów', '2017-09-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (191, '1 2 3', 'Stara Łaźnia', 'Tarnów', '2017-09-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (192, 'Pirat', 'Nie Lada Ryba', 'Olsztyn', '2017-10-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (193, 'Magiliana', 'Cibo Pazzesco', 'Sosnowiec', '2017-10-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (194, 'Le Papillon Noir', 'Der Schwarze Schmetterling', 'Katowice', '2017-10-19', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (195, 'Retka', 'Kartofel Buda', 'Łódź', '2017-10-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (196, 'Pizzeria Vicenti', 'ser-o!-mania', 'Lublin', '2017-11-02', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (197, 'Niebo w gębie i na talerzu', 'Latający Johan', 'Pabianice', '2017-11-09', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (198, 'Restauracja Quatro', 'Ziemia Brańska Gospoda', 'Brańsk', '2017-11-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (199, 'Kanion', 'Bistro Sztufada', 'Szklarska Poręba', '2017-11-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (200, 'Esencja i Smak', 'Szynk w Pszowie', 'Pszów', '2017-11-30', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (201, 'Restauracja Granola', 'Śledź i chleb', 'Gdynia', '2018-02-22', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (202, 'Restauracja Cudawianki', 'Kiełbasa i sznurek', 'Kraków', '2018-03-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (203, 'Biała Karczma', NULL, 'Michale', '2018-03-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (204, 'Sielsko Anielsko', 'Bistro Siekane', 'Sieradz', '2018-03-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (205, 'Czerwony Kapturek', 'Kotlet Bistro', 'Poznań', '2018-03-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (206, 'Restauracja Marysieńka', 'Zajazd Babski', 'Babice', '2018-03-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (207, 'Restauracja Kwadratowy Talerz', 'Bistro By the Way', 'Wrocław', '2018-04-05', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (208, 'Helios', 'Po prostu stołówka', 'Czerwionka-Leszczyny', '2018-04-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (209, 'Restauracja Ibis', 'Gospoda Kaczki za wodą', 'Goszczanów', '2018-04-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (210, 'Famiglia per amici', 'Trattoria Bandiera Italiana', 'Łódź', '2018-04-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (211, 'Bistro przy rondzie', 'Zaczarowany sad', 'Radzionków', '2018-05-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (212, 'Figa z makiem', 'Ryba z Ikrą', 'Kołobrzeg', '2018-05-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (213, 'No i Fajnie', 'Jeż i jesz', 'Zgierz', '2018-05-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (214, 'Bar Krupniok', 'Bistro Plaaaacek Chrupiący', 'Namysłów', '2018-05-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (215, 'Sjesta', 'Gospoda Kwaśnica', 'Częstochowa', '2018-09-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (216, 'Pracownia dobrych smaków – Rozmaryn', NULL, 'Szczecin', '2018-09-13', 'Pół na pół');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (217, 'Perfect Pub', 'Oberża Bażant', 'Pasłęk', '2018-09-20', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (218, 'Ziołowa Chata', 'Gospoda z górki', 'Brenna', '2018-09-27', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (219, 'Alladin’s', NULL, 'Wrocław', '2018-10-04', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (220, 'Włoszczyzna', NULL, 'Łódź', '2018-10-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (221, 'Czarny Bawół', ' Biały Bawół', 'Stare Czarnowo', '2018-10-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (222, 'James Bomba-Lina', ' Hot Burger Bistro', 'Białystok', '2018-10-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (223, 'Karuzela Smaku', ' Bielany Bielany', 'Warszawa', '2018-11-01', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (224, 'Zorba', ' Bistro Kalamata', 'Tychy', '2018-11-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (225, 'Porto di mare', ' Pieczone Gołąbki', 'Trzebinia', '2018-11-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (226, 'Szafran', ' Soczyste Pieczyste Bistro', 'Kwidzyn', '2018-11-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (227, 'Masala Twist', ' Żar Tandoori', 'Toruń', '2018-11-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (228, 'Karczma Ordynat', ' Malinowa spiżarnia', 'Wielącza', '2018-12-06', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (229, 'Hacjenda', ' Karczma Żółtodzioby', 'Słupia pod Bralinem', '2019-02-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (230, 'Taste', ' A Morze Las', 'Świnoujście', '2019-03-07', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (231, 'Dzika róża', ' Szynk u Fojermana', 'Rybnik', '2019-03-14', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (232, 'Mada', ' Bistro Granat', 'Warszawa', '2019-03-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (233, 'Paradiso', 'Karczma Kurak z Pieca', 'Kawice', '2019-03-28', 'Pół na pół');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (234, 'Zapiecek', 'Pyszny Zajazd', 'Dębówka', '2019-04-04', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (235, 'Zakątek smaku', 'Oberża dawno, dawno temu...', 'Konstantynów Łódzki', '2019-04-11', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (236, 'Pierogarnia u Marty', 'Kociewskie Jadło', 'Tczew', '2019-04-18', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (237, 'Bar Tarchomin', 'Viva Ibiza', 'Warszawa', '2019-04-25', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (238, 'Pierogarnia u Marty', 'Bistro Gniecione', 'Nowogard', '2019-05-02', 'Pół na pół');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (239, 'Pierogatka', 'Pomidorowe Bistro', 'Kalisz', '2019-05-09', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (240, 'Pod przykryfką', 'Cuba Banana', 'Gdańsk', '2019-05-16', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (241, 'Złota kura', 'Złote jajo', 'Elbląg', '2019-05-23', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (242, 'Best Bar', 'Chłop i baba', 'Ostrów Wielkopolski', '2019-09-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (243, 'Ludwinka', 'Gęś Pocztowa', 'Ludwina', '2019-09-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (244, 'Zajazd Florencja', 'Niezapominajka', 'Nowy Klincz', '2019-09-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (245, 'Gościnna Ukrainka', 'Barszcz', 'Wejherowo', '2019-09-26', 'Pół na pół');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (246, 'Tarta poducha', 'Bistro Pyszne Korzenie', 'Wrocław', '2019-10-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (247, 'Bistro Galancie', 'Mammy food', 'Łódź', '2019-10-10', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (248, 'Pod zachrypniętym kogutem', 'Pod rumianym jabłkiem', 'Glewo', '2019-10-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (249, 'Ukradli talerze', 'Kantyna. Do stołu marsz!', 'Prudnik', '2019-10-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (250, 'U Mariusza', 'Bistro w Kapuście', 'Płock', '2019-10-31', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (251, 'Vintuna', 'Nepal Bowl', 'Warszawa', '2019-11-07', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (252, 'Kuchnia z piwnicą', 'Bistro prosto z targu', 'Człuchów', '2019-11-14', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (253, 'Prova Gourmet', 'Osteria di Bitondo', 'Toruń', '2019-11-21', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (254, 'Karczma u Sołtysa', 'Bławatek', 'Duszniki-Zdrój', '2019-11-28', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (255, 'Szybka szama', 'Bistro Schadzka Przy Piecu', 'Napachanie', '2020-03-05', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (256, 'Pizza Bella', 'Oberża Dzik i Dąb', 'Ustroń', '2020-03-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (257, 'Pod Kamienicą', 'Przyjemnie podjadaj', 'Grudziądz', '2020-03-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (258, 'Bistro Smacznego', 'Bistro i Oberża Lis i kura', 'Banino', '2020-03-26', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (259, 'Trattoria da Maria', 'Trattoria "Karczochy u Marii"', 'Kraków', '2020-09-03', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (260, 'Bar "Kartuska"', 'Bistro "Podaj Kaczkę Raz!"', 'Gdańsk', '2020-09-10', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (261, 'Pub "Trops"', 'Pizzeria "di Bufala"', 'Płońsk', '2020-09-17', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (262, 'Karczma "W Podwórku"', 'Bistro "Fiołek"', 'Cegłów', '2020-09-24', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (263, 'Restauracja i Pizzeria "Amore Mio"', 'Fest Bar', 'Chorzów', '2020-10-01', 'Pół na pół');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (264, 'Chicken Flow', 'Gospoda "Zdolne łapy"', 'Łapy', '2020-10-08', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (265, 'Bistro "Na drzewiarzu"', 'Szynk na bogato', 'Jasienica', '2020-10-15', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (266, 'Gold', 'Gospoda chałupka', 'Janowo', '2020-10-22', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (267, 'Pizzeria Familijna', 'Bistro, Tłusty Indyk', 'Żerków', '2020-10-29', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (268, 'Diavolo', 'Chimmichuri American House', 'Częstochowa', '2020-11-05', 'Nieudana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (269, 'Hotel i Restauracja „Zamek"', 'Restauracja „U Rumińskiego”', 'Szczecinek', '2020-11-12', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (270, 'Pub „Barka”', 'Restauracja i smażalnia ryb „Kaczka na wodzie"', 'Piła', '2020-11-19', 'Udana');
INSERT INTO restauracje (id, nazwa_stara, nazwa_nowa, miasto, data_emisji, czy_udana) VALUES (271, 'Nowa Villa „Ostródzka”', 'W małym domku', 'Warszawa', '2020-11-26', 'Udana');